### ISSUE TITLE
Please notify the license clearly

### ISSUE THREAD

**Issue by Brian-Jurn** [notofonts/notofonts.github.io#17]
![Apache](https://user-images.githubusercontent.com/86588197/216270052-88f02cd2-3248-45d0-8892-e2c3255f3aee.png)
![OFL](https://user-images.githubusercontent.com/86588197/216270058-99ef0f06-8165-44c9-bb74-2daa767d88b7.png)

As you can see, there are 2 LICENSE files in this repository. Thus, I am confused about the license of the noto font family. I want to know whether the noto font family is OFL or not, therefore please notify the license clearly. For example, you can add an extra explanation to README.md file.

**Comment by zaddok** [comment]
Google distributes this font on the Google Fonts website with the OFL (SIL) license. One assumes Google is understanding things and distributing this correctly. But yes, it would be good if the underlying Github repository clarifies the license details.
