### ISSUE TITLE
Multiple NULL characters

### ISSUE THREAD

**Issue by moontypespace** [notofonts/notofonts.github.io#26]
### Font 
Fonts stored here: https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/googlefonts/ttf

### Where the font came from, and when
https://github.com/notofonts/notofonts.github.io/tree/main/fonts/NotoSans/googlefonts/ttf

### Font Version
Version 2.012; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
Noes not matter.

### Application name and version
Does not matter.

### Issue
There are two glyphs in the fonts 'NULL' with a unicode and 'null' without a unicode. 
Nothin major, but as I noticed it, it's worth to mention it.

### Character data
NULL
null

### Screenshot
<img width="1701" alt="Screenshot 2023-09-15 at 11 52 42" src="https://github.com/notofonts/notofonts.github.io/assets/21055547/871434e6-e613-4bac-8859-0e17605e6611">
<img width="1701" alt="Screenshot 2023-09-15 at 11 52 49" src="https://github.com/notofonts/notofonts.github.io/assets/21055547/1d0dc0d3-200f-47d5-8e2f-11af1ef52792">

**Comment by moontypespace** [comment]
It does not break any functionality.

**Comment by simoncozens** [comment]
Yeah, it's not a problem; it comes from merging two fonts both of which have NULL in them; you can see that one comes from the Latin subset and one from the Devanagari.
