### ISSUE TITLE
"Noto Looped Thai" still showing up in `index.html`

### ISSUE THREAD

**Issue by iwsfutcmd** [notofonts/notofonts.github.io#36]
(see #35)

`Noto Looped Thai` is still showing up in `index.html`. Stripping `Noto Looped Thai` out of `state.json` and `noto.json` and rerunning `build-site.py` fixes this, but rerunning `gather.py` puts `Noto Looped Thai` back into those json files, so I'm guessing the issue is https://github.com/notofonts/thai still has a "Noto Looped Thai" tag.

**Comment by iwsfutcmd** [comment]
(this will probably fix #13 too)

**Comment by simoncozens** [comment]
Should be fix after tonight's run.
