### ISSUE TITLE
fonts/NotoSansMyanmar lacks Myanmar UI

### ISSUE THREAD

**Issue by berrymot** [notofonts/notofonts.github.io#39]
notofonts/myanmar[gh-pages]/fonts does contain [a NotoSansMyanmarUI folder](https://github.com/notofonts/myanmar/tree/gh-pages/fonts/NotoSansMyanmarUI)

**Comment by simoncozens** [comment]
I'm not planning to do any more Noto Sans Myanmar UI releases; in fact we're trying to phase out UI fonts altogether. So this is a feature, not a bug...
