### ISSUE TITLE
 Fonts installed by "apt-get install fonts-noto" on Ubuntu all from this project?

### ISSUE THREAD

**Issue by garyyang85** [notofonts/notofonts.github.io#40]
Sorry for the confusion. This is not a bug, but I cannot find somewhere to ask the question. 

I am new to fonts and now I need to install fonts-noto on Ubuntu in my project. The command is "apt-get install fonts-noto", but not all the fonts installed by the command can be found in this project. For example "NotoLoopedLaoUI-SemiCondensedBold.ttf", I am wondering if all the fonts in "fonts-noto" belong to this project? Thanks.

**Comment by simoncozens** [comment]
All of the fonts in fonts-noto are part of the Noto project. Noto Looped Lao UI has been renamed to Noto Sans Lao Looped UI, and you can get it from https://notofonts.github.io/lao/ (or from this repo).
