### ISSUE TITLE
Noto Sans/Serif and Display versions are showing an incorrect diacritical mark in the Vietnamese language

### ISSUE THREAD

**Issue by kereder** [notofonts/notofonts.github.io#41]
## Defect Report

> Noto fonts can be obtained from https://notofonts.github.io/
> If you find a problem with a released font, then please use this template to file a defect report.
> Before filing your report, please check if the issue has been fixed in the latest development build. You can get development builds by finding the font family on https://notofonts.github.io/ and following the link to "Development builds".

### Title 
Noto Sans/Serif and Display versions are showing an incorrect diacritical mark in the Vietnamese language

### Font 
- NotoSansDisplay.ttf (all fontstyles)
- NotoSans.ttf (all fontstyles)
- NotoSerifDisplay.ttf (all fontstyles)
- NotoSerif.ttf (all fontstyles)

### Where the font came from, and when
https://fonts.google.com/noto, Date: 2024-02-16
https://fonts.google.com/selection?noto.query=noto+sans+display, Date: 2023-09-15

### Font Version
N/A

### OS name and version
MacOS: 14.2.1

### Issue
  1. If you use Noto Sans/Serif/Display to set Vietnamese texts, the character "ề" is displayed incorrectly.
  2. In the Screenshot I show the incorrect version and the correct version from an other font.
  

### Character data
Vietnamese text: 
Mọi con mắt đều đổ dồn vào đội Fronius của bạn!
This character ist wrong in Noto Sans/Serif/Display: ề

### Screenshot
see attached
![Screenshot_ề_Vietnamese](https://github.com/notofonts/notofonts.github.io/assets/167405710/9e894682-b534-44b4-bb1f-8aefd10ae67d)

**Comment by simoncozens** [comment]
This is a stylistic choice; according to Donny Truong's [Vietnamese Typography](https://vietnamesetypography.com/design-challenges/):

> The position of the diacritical marks can vary. As illustrated here, accents can be placed on the right side of a circumflex, on either side (usually an acute on the right and a grave on the left), or on the top. Accents on the right are ideal for consistency and the natural flow of text. Accents on either side are more distinguishable, but might slow down the process of saccades. Accents on the top are more balanced, but might affect the leading. For the ease and comfort of reading, accents (including a hook above) positioned consistently on the right are recommended, but type designers should choose the positions that best fit their design.

As well as showing Noto Serif in his site, he also gives the example of Spectral by Production Type which has grave accents on the left of the circumflex.

<img width="1009" alt="Screenshot 2024-04-18 at 09 44 01" src="https://github.com/notofonts/notofonts.github.io/assets/106728/b184f864-b30b-4883-aca0-f8ce69f45e2d">
