### ISSUE TITLE
Latin Only version - Noto Sans

### ISSUE THREAD

**Issue by abhishek-junghare** [notofonts/notofonts.github.io#43]
**Is your feature request related to a problem? Please describe.**
Considering that the Noto Sans Variable sizes are around 2.5MB, I prefer static styles. Even then, each style is about 500KB in TTF and 100KB in WOFF. Now, if we consider the usual 'Regular' & 'Bold' weights, which are often the only weights being used, it becomes 1MB in TTF and 200KB in WOFF. So, it's not really good in terms of size optimization.

**Describe the solution you'd like**
Noto Sans is already available in languages like Hebrew, Devanagari, etc. I suggest releasing a version with just Latin characters.

**Describe alternatives you've considered**
I tried https://transfonter.org/ to limit characters to Latin only, but it would always be better to get this via the source itself.

**Comment by abhishek-junghare** [comment]
> you may be interested in https://github.com/notofonts/latin-greek-cyrillic/

That's not for the general audience who want downloadable TTF files or access via CDN, who might not even know that these versions exist on GitHub.

**Comment by simoncozens** [comment]
Oh, I see what you want - *just* Latin, i.e. no Greek or Cyrillic in https://github.com/notofonts/notofonts.github.io/blob/main/fonts/NotoSans/hinted/ttf/NotoSans-Regular.ttf?

I think if you want that, it's better to make it yourself; it's not something we're likely to want to produce. Besides, the majority of the Noto Sans glyphs are actually Latin; the Greek and Cyrillic are quite small. It's just that there's a *lot* of Latin codepoints in Unicode...

**Comment by kenmcd** [comment]
> So, it's not really good in terms of size optimization

For what purpose?
The web font API already provides latn subset fonts.

**Comment by aelatham** [comment]
Please close this. Use a font editor to delete the characters you don't want in Noto Sans/Serif/Mono (no suffix, Latin/Greek/Cyrillic).

**Comment by simoncozens** [comment]
Yes, or better hb-subset.
