### ISSUE TITLE
Noto Sans Arabic UI can not be found

### ISSUE THREAD

**Issue by alitajelsir** [notofonts/notofonts.github.io#44]
**Is your feature request related to a problem? Please describe.**
Noto Sans Arabic UI is absent from the repo and can only be found in the development builds.

**Describe the solution you'd like**
Add Noto Sans Arabic UI to the repo.

**Comment by aelatham** [comment]
See #39.

**Comment by alitajelsir** [comment]
> See #39. @simoncozens, please close as "not planned".
- The problem is: regular fonts have higher vertical spaces compared to their UI counterparts.
- Sometimes their is UI inconsistencies if different fonts are used for different languages. for example:
	- This is the UI with `Noto Sans Arabic UI`:
		![Screenshot_20240518_104801](https://github.com/notofonts/notofonts.github.io/assets/26362874/af8ffcd6-df8b-4d0f-8310-13ef9253a63f)
	- This is with `Noto Sans Arabic`:
		![Screenshot_20240518_104957](https://github.com/notofonts/notofonts.github.io/assets/26362874/b402c07a-1a22-4a7d-974a-7edfb2da4c62)
	- In both cases `Noto Sans` was used for English
- Is there anyway I can make the regular fonts behave as same as their UI counterparts?
- However, I totally respect what the developers decide for their project. Your time and effort are much appreciated. Thanks in advance!.

**Comment by simoncozens** [comment]
This is a problem with the operating system, which is aligning text boxes according to the top of the font's vertical metrics instead of according to the text baseline.

"UI fonts" only exist to work around the problems of bad tall/deep script support in text renderers; the fix is for UI developers to handle these fonts better.
