### ISSUE TITLE
Made some Noto-compatible Todhri

### ISSUE THREAD

**Issue by Mercury13** [notofonts/notofonts.github.io#47]
- Metrically compatible with Noto
- Made in Inkscape + FontForge
- One weight
- Fully working, but method of hanging double macron is different from Noto LGC
- Letters R and RR are doubtful (printed sources use glyphs that wildly vary from handwritten)
- Because of doubtful letters, only default hangouts are made, no kerning

![image](https://github.com/notofonts/notofonts.github.io/assets/10164882/0268dac7-4121-4d1b-bf72-b1c7eed7cdb2)

**Comment by simoncozens** [comment]
Very cool. Wanna contribute it?

**Comment by Mercury13** [comment]
Yes, it’s completely free, but I’ll need help.

1. Those letters R and RR — how to draw them? R is drawn by printed sources, and RR by handwritten. Need more research work, RR is rare. E.g. B is attested with both connected and diverging ends, and when I tried to write it quickly, its ends tend to diverge, that’s why I drew it in such a fashion.
2. There will always be troubles converting from one format to another.

**Comment by simoncozens** [comment]
(2) is easy, I've got good tooling for converting Fontforge to Glyphs/UFO now.

**Comment by Mercury13** [comment]
Which curves are better: quad or cubic?

**Comment by simoncozens** [comment]
Normally we use cubic for source, quad for binary.

**Comment by Mercury13** [comment]
Converted to cubic, deleted unneeded glyphs leaving only good — in the night I’ll clean up tables. What’s next?

**Comment by Mercury13** [comment]
Started Ol Onal, but IDK when I’m ready. I made Todhri approx. in 2 weeks, Ol Onal will be in 1+mo.

**Comment by Mercury13** [comment]
Just four Onao letters for now.
![image](https://github.com/user-attachments/assets/55379982-dbbf-4caf-8396-0a66e20cce26)

**Comment by Mercury13** [comment]
Did thirteen letters for now and took this placard as a main base, but I still doubt: Eastern fonts often have thick HORIZONTAL stems.
![image](https://github.com/user-attachments/assets/a26a2bbb-7b85-4ba7-ae8d-e3ebb761d87a)

**Comment by Mercury13** [comment]
Decision made, switching to inverse contrast!
![image](https://github.com/user-attachments/assets/709a0756-34d9-4a5f-b91d-88742d23e07f)

**Comment by Mercury13** [comment]
Made Ol Onal almost completely, but stuck on digits now. I wanted to make them metrically compatible with normal Noto, but if something fails, I’ll be forced to redraw outlines rather than fix bearings.
