### ISSUE TITLE
MegaMerge font display issue

### ISSUE THREAD

**Issue by RampantDespair** [notofonts/notofonts.github.io#59]
I'm not font-savvy so if the answer to my question is glaring I do apologize.

When loading the `fonts\\NotoSans\\full\\variable-ttf\\NotoSans[wdth,wght].ttf` file I get the following:
![image](https://github.com/user-attachments/assets/0b93cd50-6645-4327-ad1f-8ffa06087a8c)

However when I load the `megamerge\\NotoSansLiving-Regular.ttf` file I get this:
![image](https://github.com/user-attachments/assets/b3fc6c94-ca45-4346-b918-5c0f72ac5a35)

Important to note that I am loading both fonts the **exact same way**.

I saw that on the megamerge README, the following is stated
> Vertical metrics are removed.

Is that what's causing the behavior showed above? 
And if so is there I way to fix this?

**Comment by simoncozens** [comment]
`fontTools.merger`, used by the megamerge script, sets the vertical metrics of the output font to be the highest and deepest values of all the fonts used for merging. This is arguably the correct behaviour; if you set the vertical metrics to make the Latin part of Noto Sans Living look the same as Noto Sans LGC, it will create overlaps between lines when tall and deep characters are used.

So the way to fix this is to make the font size bigger. :-)

**Comment by RampantDespair** [comment]
@simoncozens 
That's interesting, because I am looking for a one-size fits all solution when it comes to fonts.
I want to let the user pick their language, without having to load and unload different files.

Do you believe it would be possible to detect, through mathematical formulas what the font size should be based on the character set being used?
Example let's say the english language was picked, would it be possible to calculate what the font size should be so that it looks correct (referencing the pictures on my post above)?

**Comment by simoncozens** [comment]
I don't know enough about what you're doing (browser? app? some kind of programming framework?) to give detailed advice, but you need to understand how your environment handles font vertical metrics. [This article](https://type.today/en/journal/verticalmetrics) together with the links in the bibliography would be a good place to start learning. In CSS there is a `font-size-adjust` property which does what you are thinking of, but I would suggest understanding the vertical metrics problem in more depth before starting to fiddle.

**Comment by RampantDespair** [comment]
@simoncozens 
It's a c++ desktop application using ImGUI and rendered with DX12. 
So web-related utilities aren't particularly accessible

**Comment by simoncozens** [comment]
Okay, I'm well out of my depth here. Consult your ImGUI manual for details of how it sizes fonts based on their vertical metrics.

**Comment by RampantDespair** [comment]
@simoncozens 
Alright, thank you for time, appreciate it.
