### ISSUE TITLE
Add site nav to top bar

### ISSUE THREAD

**Issue by davelab6** [notofonts/notofonts.github.io#6]
The top bar currently has only a title and a right-end filter menu:

<img width="1771" alt="Screen Shot 2022-11-08 at 11 11 56 AM" src="https://user-images.githubusercontent.com/261579/200642814-896c929d-0e5b-41f3-96d3-9428f7f42878.png">

In #5 I suggest a better design for the filter; the top bar (and entire page) is also lacking links (or I can't find them ;) to the other 2 pages on the site:

- https://notofonts.github.io/overview
- https://notofonts.github.io/analytics

I suggest moving the title to the left-end, and having 3 links as title buttons (like GF catalog top bar) in the middle; and then page-specific nav (like the filter icon to open a mega menu on this page, and the codepoint sort order on the overview page) on the right.

     Noto Dashboard       dashboard | overview | analytics          filter

**Comment by simoncozens** [comment]
Done
