### ISSUE TITLE
feat: add a loading indicator to the overview page

### ISSUE THREAD

**Issue by Rexogamer** [notofonts/notofonts.github.io#8]
**Is your feature request related to a problem? Please describe.**
I took a look at the overview page - for several seconds (while the data was loading/rendering), I only saw a white screen - I assumed that the data wasn't loading and went to turn off my adblocker until it finally appeared.

**Describe the solution you'd like**
It'd probably be a good idea to add a loading indicator. It doesn't have to be anything fancy - some bolded text would suffice.

**Describe alternatives you've considered**
It might also be a good idea to try and speed up the loading process a bit, although I appreciate that this might not be easy/feasible.

**Comment by simoncozens** [comment]
I haven't exactly fixed this, but I've stopped creating all the tiny dots for the CJK Unified Ideographics, which is what was taking up all the time.
